"""Implemented MISRA C++:2023 checks, based on the supplied 2023 edition.

Descriptions are scanner summaries. Coverage describes the lexical subset,
not a claim of complete enforcement of the corresponding guideline.
"""

STANDARD = "MISRA C++:2023"
PREFIX = "MISRA-CPP-"

# number, class, area, title, rationale, remediation, implemented coverage
SPECS = [
    ("5.7.1", "Required", "Comments", "Nested block-comment opener",
     "A nested opener can hide code that appears executable.",
     "Remove the nested opener and close each block comment.", "Literal /* inside a block comment."),
    ("5.7.3", "Required", "Comments", "Line splice in a line comment",
     "A trailing backslash makes the next physical line part of the comment.",
     "Remove the backslash immediately before the newline.", "Backslash-newline inside // comments."),
    ("5.13.3", "Required", "Literals", "Octal integer literal",
     "A leading zero changes the numeric base and can disguise the intended value.",
     "Use decimal or hexadecimal notation; a single zero is permitted.", "Integer tokens, including digit separators; excludes zero and escapes."),
    ("5.13.5", "Required", "Literals", "Literal suffix starts with lowercase l",
     "Lowercase l can be confused with the digit one.",
     "Use uppercase L at the start of a literal suffix.", "Numeric suffixes; permits Ull and user-defined suffixes."),
    ("7.11.1", "Required", "Types", "Legacy NULL macro",
     "An integer null constant can select an unintended overload.",
     "Use nullptr for null pointers.", "NULL tokens only; zero-valued pointer expressions require type analysis."),
    ("8.2.2", "Required", "Conversions", "C-style or functional scalar cast",
     "Older cast syntax hides conversion intent and permits unsafe conversions.",
     "Use a suitable named C++ cast or brace initialization.", "Built-in scalar types only; permits (void) and brace initialization."),
    ("8.2.5", "Required", "Conversions", "Potentially prohibited reinterpret_cast",
     "Reinterpreting unrelated types can violate object representation and aliasing requirements.",
     "Use a type-safe conversion or verify a documented rule exception.", "Pointer/reference targets; exempts byte/character/void pointer targets. Integral targets need target-width analysis."),
    ("9.6.1", "Advisory", "Control flow", "Use of goto",
     "Unstructured jumps complicate reasoning about control flow.",
     "Restructure the function using structured control flow.", "goto keyword."),
    ("10.3.1", "Advisory", "Namespaces", "Unnamed namespace in a header",
     "Each translation unit receives a distinct entity from this namespace.",
     "Move the unnamed namespace into a source file.", "Unnamed and inline unnamed namespace definitions in headers."),
    ("10.4.1", "Required", "Portability", "Inline assembly declaration",
     "Assembly declarations rely on implementation-specific behavior.",
     "Use portable C++ or reviewed platform intrinsics.", "asm keyword; vendor extensions are outside this check."),
    ("12.3.1", "Required", "Types", "Use of union",
     "Accessing an inactive union member can violate object lifetime rules.",
     "Use std::variant or a structure with explicit state.", "union keyword."),
    ("16.5.1", "Required", "Operators", "Overloaded logical operator",
     "Overloaded logical operators evaluate both operands.",
     "Use a named operation or built-in boolean operators.", "operator &&, ||, and, or declarations and explicit uses."),
    ("18.5.2", "Advisory", "Library", "Explicit program termination",
     "Abrupt termination can bypass destructors and leave resources unreleased.",
     "Return through normal shutdown or document the safety architecture's termination policy.", "abort, exit, _Exit, quick_exit, terminate calls and address uses."),
    ("19.0.2", "Required", "Preprocessor", "Function-like macro definition",
     "Macros bypass C++ scope and type checking.",
     "Use an inline function, constexpr function or template.", "#define with an immediately adjacent parameter list."),
    ("19.0.4", "Advisory", "Preprocessor", "Undefining a macro not defined in this file",
     "Changing an externally supplied macro couples the file to its inclusion context.",
     "Only undefine macros defined earlier in the same file.", "Physical directive order; conditional branches are not evaluated."),
    ("19.1.2", "Required", "Preprocessor", "Unmatched conditional directive",
     "Conditional groups spanning files make preprocessing fragile.",
     "Keep each conditional group complete within one file.", "Unmatched #if/#ifdef/#ifndef/#elif/#else/#endif; no preprocessing."),
    ("19.3.1", "Advisory", "Preprocessor", "Macro stringizing or token pasting",
     "Token construction obscures the code that will be compiled.",
     "Use typed language facilities instead of # or ## macro operators.", "# and ## in macro replacement lists, including continuations."),
    ("19.6.1", "Advisory", "Preprocessor", "Pragma directive or operator",
     "Pragmas introduce implementation-specific behavior.",
     "Use portable language features and include guards.", "#pragma and _Pragma, including pragma once."),
    ("21.2.1", "Required", "Library", "Unchecked C numeric conversion",
     "These conversions cannot report all conversion failures reliably.",
     "Use std::from_chars and check its result.", "atof, atoi, atol, atoll calls and address uses."),
    ("21.2.3", "Required", "Library", "Use of system",
     "Shell execution depends on the environment and may execute unintended commands.",
     "Replace shell execution with a controlled platform interface.", "system calls and address uses."),
    ("21.2.4", "Required", "Library", "Use of offsetof",
     "Manual layout assumptions restrict portability and type safety.",
     "Access members through the type's interface.", "offsetof tokens outside include names."),
    ("21.6.1", "Advisory", "Memory", "Explicit dynamic allocation or deallocation",
     "Dynamic allocation introduces lifetime, fragmentation and timing risks.",
     "Prefer fixed storage or document and control dynamic allocation.", "Ordinary new/delete, C allocation APIs, std::make_unique/shared. Placement new and implicit container allocations are not checked."),
    ("21.10.1", "Required", "Library", "C variable-argument facility",
     "C variable arguments bypass normal argument type checking.",
     "Use typed parameters or variadic templates.", "va_list, va_arg, va_start, va_end, va_copy tokens; ellipsis alone is permitted."),
    ("21.10.2", "Required", "Library", "Non-local C jump facility",
     "Non-local jumps can bypass C++ object destruction.",
     "Use structured control flow or appropriate exception handling.", "Direct csetjmp/setjmp.h includes and jmp_buf/setjmp/longjmp uses."),
    ("24.5.2", "Required", "Library", "Raw memory copy or comparison",
     "Byte operations can violate object semantics or compare padding.",
     "Use typed assignment, comparison or appropriate algorithms.", "memcpy, memmove, memcmp calls and address uses."),
    ("25.5.1", "Required", "Library", "Changing the global locale",
     "Global locale changes can race with operations in other threads.",
     "Pass a locale to the operation that needs it.", "setlocale and explicitly qualified std::locale::global calls."),
    ("26.3.1", "Advisory", "Containers", "std::vector<bool> specialization",
     "The packed specialization has different reference and concurrency behavior.",
     "Use a byte or boolean wrapper container, std::array or std::bitset.", "Explicit std::vector<bool, ...> spelling; aliases are not resolved."),
    ("30.0.1", "Required", "Library", "C stream input/output facility",
     "C stream operations expose unspecified and implementation-dependent behavior.",
     "Use suitable C++ stream interfaces with checked errors.", "Named cstdio and wide-character I/O functions; calls and address uses."),
]

COVERAGE = {PREFIX + row[0]: row[6] for row in SPECS}
